### PR TITLE
Make filesystem repository searchable

### PR DESCRIPTION
**Pull request by keineahnung2345**
In current version, filesystem repository is not searchable. And this PR is my attempt to make it searchable, this works, but my `validates :changeset_id, presence: true` is somehow bruteforce. Can you suggest so it will conform to the original codebase? Thank you.

### CODE REVIEW

**Comment by picman** [comment]
I don't use this feature. I think that your code is Okay.

**Comment by picman** [comment]
Are you still working on this? It's marked with WIP.

**Comment by keineahnung2345** [comment]
I pushed two additional commits to fix some bugs.
Also I've merged devel-2.0.5 into this branch, please help me to change the base branch, thanks.

**Comment by picman** [comment]
Thank you,

**Pull request merged**
